### ISSUE TITLE
io.crashbox:simplesql_3:0.4.0 is not found in maven central

### ISSUE THREAD

**Issue by a01fe** [jodersky/simplesql#6]
`io.crashbox:simplesql_3:0.4.0`, as mentioned in `README.md`, is not found in maven central.

For example, with this in `project.scala`:

```scala
//> using dep io.crashbox::simplesql:0.4.0
```

`scala-cli compile .` fails with:

```plain text
$ scala-cli compile .
Downloading 2 dependencies
[error] ./project.scala:1:15
[error] Error downloading io.crashbox:simplesql_3:0.4.0
[error]   not found: /Users/finchr/Library/Caches/ScalaCli/local-repo/1.5.1/io.crashbox/simplesql_3/0.4.0/ivys/ivy.xml
[error]   No fallback URL found
[error]   not found: /Users/finchr/.ivy2/local/io.crashbox/simplesql_3/0.4.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/io/crashbox/simplesql_3/0.4.0/simplesql_3-0.4.0.pom
[error] //> using dep io.crashbox::simplesql:0.4.0
[error]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
$
```

**Comment by jodersky** [comment]
Thanks for the bug report. Indeed, it does not show up [in the package repo](https://repo1.maven.org/maven2/io/crashbox/simplesql_3/).

I remember having some issues with sonatype last time I published a version. It failed for a few days, but eventually it did appear to succeed, but maybe that was an illusion. Anyway, I'll re-publish.

**Comment by jodersky** [comment]
I migrated to the new sonatype portal, which seems to be mores stable. It should be good now.

**Comment by a01fe** [comment]
Looks good, ty!
